SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;
SET NOCOUNT ON;

IF OBJECT_ID(N'dbo.Phong', N'U') IS NULL OR COL_LENGTH(N'dbo.Phong', N'GiaPhong') IS NULL
    THROW 50140, N'Chạy migrations 001-008 trước khi seed master.', 1;

MERGE dbo.Phong AS target
USING (VALUES
    (N'A101', N'Nam', 6, N'Không có', N'A', N'Trống'),
    (N'A102', N'Nam', 8, N'1', N'A', N'Trống'),
    (N'A103', N'Nam', 4, N'-', N'A', N'Đầy'),
    (N'A104', N'Nam', 6, N'Không có', N'A', N'Trống'),
    (N'A105', N'Nam', 8, N'1', N'A', N'Trống'),
    (N'A201', N'Nữ', 4, N'2', N'A', N'Trống'),
    (N'A202', N'Nữ', 8, N'2', N'A', N'Trống'),
    (N'A203', N'Nữ', 6, N'2', N'A', N'Trống'),
    (N'A204', N'Nữ', 6, N'Phòng tầng 2', N'A', N'Đầy'),
    (N'A205', N'Nữ', 8, N'Phòng tầng 2', N'A', N'Trống'),
    (N'A301', N'Nam', 6, N'3', N'A', N'Trống'),
    (N'A302', N'Nam', 8, N'Phòng tầng 3', N'A', N'Trống'),
    (N'A303', N'Nam', 4, N'Phòng tầng 3', N'A', N'Trống'),
    (N'A304', N'Nam', 6, N'Phòng tầng 3', N'A', N'Trống'),
    (N'A305', N'Nam', 8, N'Phòng tầng 3', N'A', N'Trống'),
    (N'A401', N'Nữ', 6, N'Phòng tầng 4', N'A', N'Trống'),
    (N'A402', N'Nữ', 8, N'Phòng tầng 4', N'A', N'Trống'),
    (N'A403', N'Nữ', 8, N'Phòng tầng 4', N'A', N'Trống'),
    (N'A404', N'Nữ', 6, N'Phòng tầng 4', N'A', N'Trống'),
    (N'A405', N'Nữ', 8, N'Phòng tầng 4', N'A', N'Trống'),
    (N'A501', N'Nam', 6, N'Phòng tầng 5', N'A', N'Trống'),
    (N'A502', N'Nam', 8, N'Phòng tầng 5', N'A', N'Trống'),
    (N'A503', N'Nam', 6, N'Phòng tầng 5', N'A', N'Trống'),
    (N'A504', N'Nam', 6, N'Phòng tầng 5', N'A', N'Trống'),
    (N'A505', N'Nam', 8, N'Phòng tầng 5', N'A', N'Trống'),
    (N'A601', N'Nữ', 6, N'Phòng tầng 6', N'A', N'Trống'),
    (N'A602', N'Nữ', 8, N'Phòng tầng 6', N'A', N'Trống'),
    (N'A603', N'Nữ', 4, N'Phòng tầng 6', N'A', N'Trống'),
    (N'A604', N'Nữ', 6, N'Phòng tầng 6', N'A', N'Trống'),
    (N'A605', N'Nữ', 8, N'Phòng tầng 6', N'A', N'Trống'),
    (N'A701', N'Nam', 6, N'Phòng tầng 7', N'A', N'Trống'),
    (N'A702', N'Nam', 8, N'Phòng tầng 7', N'A', N'Đầy'),
    (N'A703', N'Nam', 4, N'Phòng tầng 7', N'A', N'Đầy'),
    (N'A704', N'Nam', 8, N'Phòng tầng 7', N'A', N'Đầy'),
    (N'A705', N'Nam', 8, N'Phòng tầng 7', N'A', N'Trống'),
    (N'A801', N'Nữ', 6, N'Phòng tầng 8', N'A', N'Đầy'),
    (N'A802', N'Nữ', 8, N'Phòng tầng 8', N'A', N'Trống'),
    (N'A803', N'Nữ', 4, N'Phòng tầng 8', N'A', N'Trống'),
    (N'A804', N'Nữ', 8, N'Phòng tầng 8', N'A', N'Trống'),
    (N'A805', N'Nữ', 8, N'Phòng tầng 8', N'A', N'Trống'),
    (N'A901', N'Nam', 6, N'Phòng tầng 9', N'A', N'Trống'),
    (N'A902', N'Nam', 8, N'Phòng tầng 9', N'A', N'Trống'),
    (N'A903', N'Nam', 4, N'Phòng tầng 9', N'A', N'Trống'),
    (N'A904', N'Nam', 6, N'Phòng tầng 9', N'A', N'Trống'),
    (N'A905', N'Nam', 8, N'Phòng tầng 9', N'A', N'Trống'),
    (N'B101', N'Nam', 6, N'Phòng tầng 1', N'B', N'Đầy'),
    (N'B102', N'Nam', 8, N'Phòng tầng 1', N'B', N'Trống'),
    (N'B103', N'Nam', 4, N'Phòng tầng 1', N'B', N'Trống'),
    (N'B104', N'Nam', 6, N'Phòng tầng 1', N'B', N'Trống'),
    (N'B105', N'Nam', 8, N'Phòng tầng 1', N'B', N'Đầy'),
    (N'B201', N'Nữ', 6, N'Phòng tầng 2', N'B', N'Trống'),
    (N'B202', N'Nữ', 8, N'Phòng tầng 2', N'B', N'Trống'),
    (N'B203', N'Nữ', 8, N'Phòng tầng 2', N'B', N'Trống'),
    (N'B204', N'Nữ', 8, N'Phòng tầng 2', N'B', N'Đầy'),
    (N'B205', N'Nữ', 8, N'Phòng tầng 2', N'B', N'Trống'),
    (N'B301', N'Nam', 6, N'Phòng tầng 3', N'B', N'Trống'),
    (N'B302', N'Nam', 8, N'Phòng tầng 3', N'B', N'Trống'),
    (N'B303', N'Nam', 4, N'Phòng tầng 3', N'B', N'Trống'),
    (N'B304', N'Nam', 6, N'Phòng tầng 3', N'B', N'Trống'),
    (N'B305', N'Nam', 8, N'Phòng tầng 3', N'B', N'Trống'),
    (N'B401', N'Nữ', 6, N'Phòng tầng 4', N'B', N'Trống'),
    (N'B402', N'Nữ', 8, N'Phòng tầng 4', N'B', N'Trống'),
    (N'B403', N'Nữ', 4, N'Phòng tầng 4', N'B', N'Trống'),
    (N'B404', N'Nữ', 6, N'Phòng tầng 4', N'B', N'Trống'),
    (N'B405', N'Nữ', 8, N'Phòng tầng 4', N'B', N'Trống'),
    (N'B501', N'Nam', 6, N'Phòng tầng 5', N'B', N'Trống'),
    (N'B502', N'Nam', 8, N'Phòng tầng 5', N'B', N'Trống'),
    (N'B503', N'Nam', 4, N'Phòng tầng 5', N'B', N'Đầy'),
    (N'B504', N'Nam', 6, N'Phòng tầng 5', N'B', N'Trống'),
    (N'B505', N'Nam', 8, N'Phòng tầng 5', N'B', N'Trống'),
    (N'B601', N'Nữ', 6, N'Phòng tầng 6', N'B', N'Đầy'),
    (N'B602', N'Nữ', 8, N'Phòng tầng 6', N'B', N'Trống'),
    (N'B603', N'Nữ', 6, N'Phòng tầng 6', N'B', N'Trống'),
    (N'B604', N'Nữ', 6, N'Phòng tầng 6', N'B', N'Trống'),
    (N'B605', N'Nữ', 8, N'Phòng tầng 6', N'B', N'Trống'),
    (N'B701', N'Nam', 8, N'Phòng tầng 7', N'B', N'Đầy'),
    (N'B702', N'Nam', 8, N'Phòng tầng 7', N'B', N'Trống'),
    (N'B703', N'Nam', 8, N'Phòng tầng 7', N'B', N'Trống'),
    (N'B704', N'Nam', 6, N'Phòng tầng 7', N'B', N'Trống'),
    (N'B705', N'Nam', 8, N'Phòng tầng 7', N'B', N'Trống'),
    (N'B801', N'Nữ', 6, N'Phòng tầng 8', N'B', N'Trống'),
    (N'B802', N'Nữ', 8, N'Phòng tầng 8', N'B', N'Trống'),
    (N'B803', N'Nữ', 4, N'Phòng tầng 8', N'B', N'Trống'),
    (N'B804', N'Nữ', 6, N'Phòng tầng 8', N'B', N'Trống'),
    (N'B805', N'Nữ', 8, N'Phòng tầng 8', N'B', N'Trống'),
    (N'B901', N'Nam', 8, N'Phòng tầng 9', N'B', N'Đầy'),
    (N'B902', N'Nam', 8, N'Phòng tầng 9', N'B', N'Trống'),
    (N'B903', N'Nam', 4, N'Phòng tầng 9', N'B', N'Trống'),
    (N'B904', N'Nam', 6, N'Phòng tầng 9', N'B', N'Trống'),
    (N'B905', N'Nam', 8, N'Phòng tầng 9', N'B', N'Trống'),
    (N'C101', N'Nam', 8, N'Phòng tầng 1', N'C', N'Trống'),
    (N'C102', N'Nam', 8, N'Phòng tầng 1', N'C', N'Trống'),
    (N'C103', N'Nam', 4, N'Phòng tầng 1', N'C', N'Trống'),
    (N'C104', N'Nam', 6, N'Phòng tầng 1', N'C', N'Trống'),
    (N'C105', N'Nam', 8, N'Phòng tầng 1', N'C', N'Trống'),
    (N'C201', N'Nữ', 6, N'Phòng tầng 2', N'C', N'Trống'),
    (N'C202', N'Nữ', 8, N'Phòng tầng 2', N'C', N'Trống'),
    (N'C203', N'Nữ', 4, N'Phòng tầng 2', N'C', N'Đầy'),
    (N'C204', N'Nữ', 6, N'Phòng tầng 2', N'C', N'Trống'),
    (N'C205', N'Nữ', 8, N'Phòng tầng 2', N'C', N'Trống'),
    (N'C301', N'Nam', 6, N'Phòng tầng 3', N'C', N'Trống'),
    (N'C302', N'Nam', 8, N'Phòng tầng 3', N'C', N'Trống'),
    (N'C303', N'Nam', 6, N'Phòng tầng 3', N'C', N'Đầy'),
    (N'C304', N'Nam', 6, N'Phòng tầng 3', N'C', N'Trống'),
    (N'C305', N'Nam', 8, N'Phòng tầng 3', N'C', N'Trống'),
    (N'C401', N'Nữ', 8, N'Phòng tầng 4', N'C', N'Trống'),
    (N'C402', N'Nữ', 8, N'Phòng tầng 4', N'C', N'Trống'),
    (N'C403', N'Nữ', 8, N'Phòng tầng 4', N'C', N'Đầy'),
    (N'C404', N'Nữ', 6, N'Phòng tầng 4', N'C', N'Trống'),
    (N'C405', N'Nữ', 8, N'Phòng tầng 4', N'C', N'Trống'),
    (N'C501', N'Nam', 6, N'Phòng tầng 5', N'C', N'Đầy'),
    (N'C502', N'Nam', 8, N'Phòng tầng 5', N'C', N'Trống'),
    (N'C503', N'Nam', 4, N'Phòng tầng 5', N'C', N'Trống'),
    (N'C504', N'Nam', 6, N'Phòng tầng 5', N'C', N'Trống'),
    (N'C505', N'Nam', 8, N'Phòng tầng 5', N'C', N'Trống'),
    (N'C601', N'Nữ', 6, N'Phòng tầng 6', N'C', N'Trống'),
    (N'C602', N'Nữ', 8, N'Phòng tầng 6', N'C', N'Trống'),
    (N'C603', N'Nữ', 4, N'Phòng tầng 6', N'C', N'Trống'),
    (N'C604', N'Nữ', 8, N'Phòng tầng 6', N'C', N'Đầy'),
    (N'C605', N'Nữ', 8, N'Phòng tầng 6', N'C', N'Trống'),
    (N'C701', N'Nam', 6, N'Phòng tầng 7', N'C', N'Trống'),
    (N'C702', N'Nam', 8, N'Phòng tầng 7', N'C', N'Trống'),
    (N'C703', N'Nam', 4, N'7', N'C', N'Trống'),
    (N'C704', N'Nam', 6, N'Phòng tầng 7', N'C', N'Trống'),
    (N'C705', N'Nam', 8, N'Phòng tầng 7', N'C', N'Trống'),
    (N'C801', N'Nữ', 6, N'Phòng tầng 8', N'C', N'Đầy'),
    (N'C802', N'Nữ', 8, N'Phòng tầng 8', N'C', N'Trống'),
    (N'C803', N'Nữ', 4, N'Phòng tầng 8', N'C', N'Trống'),
    (N'C804', N'Nữ', 6, N'Phòng tầng 8', N'C', N'Trống'),
    (N'C805', N'Nữ', 8, N'Phòng tầng 8', N'C', N'Trống'),
    (N'C901', N'Nam', 6, N'Phòng tầng 9', N'C', N'Trống'),
    (N'C902', N'Nam', 8, N'Phòng tầng 9', N'C', N'Trống'),
    (N'C903', N'Nam', 4, N'Phòng tầng 9', N'C', N'Trống'),
    (N'C904', N'Nam', 6, N'Phòng tầng 9', N'C', N'Trống'),
    (N'C905', N'Nam', 8, N'Phòng tầng 9', N'C', N'Trống'),
    (N'D101', N'Nam', 4, N'Phòng mới tạo', N'A', N'Ngưng sử dụng'),
    (N'D102', N'Nam', 4, N'New', N'B', N'Ngưng sử dụng')
) AS source (TenPhong, LoaiPhong, SucChuaToiDa, GhiChu, Khu, TrangThaiGoc)
ON target.TenPhong = source.TenPhong
WHEN MATCHED THEN
    UPDATE SET LoaiPhong = source.LoaiPhong,
               SucChuaToiDa = source.SucChuaToiDa,
               SoSinhVienHienTai = 0,
               TrangThaiPhong = CASE WHEN source.TrangThaiGoc IN (N'Ngưng sử dụng', N'Bảo trì')
                                    THEN source.TrangThaiGoc ELSE N'Trống' END,
               GhiChu = source.GhiChu,
               Khu = source.Khu,
               GiaPhong = CASE source.SucChuaToiDa
                   WHEN 4 THEN CONVERT(decimal(18,2), 1200000)
                   WHEN 6 THEN CONVERT(decimal(18,2), 800000)
                   WHEN 8 THEN CONVERT(decimal(18,2), 500000)
                   ELSE CONVERT(decimal(18,2), 0)
               END
WHEN NOT MATCHED THEN
    INSERT (TenPhong, LoaiPhong, SucChuaToiDa, SoSinhVienHienTai, TrangThaiPhong, GhiChu, Khu, GiaPhong)
    VALUES (source.TenPhong, source.LoaiPhong, source.SucChuaToiDa, 0,
            CASE WHEN source.TrangThaiGoc IN (N'Ngưng sử dụng', N'Bảo trì')
                 THEN source.TrangThaiGoc ELSE N'Trống' END,
            source.GhiChu, source.Khu,
            CASE source.SucChuaToiDa
                WHEN 4 THEN CONVERT(decimal(18,2), 1200000)
                WHEN 6 THEN CONVERT(decimal(18,2), 800000)
                WHEN 8 THEN CONVERT(decimal(18,2), 500000)
                ELSE CONVERT(decimal(18,2), 0)
            END);
GO